# Generated by Django 6.0.8 on 2026-08-06 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
